COMMON:
  GPU: '0'
  saved_dir: "/home/hoangbm/checkpoint/pose-estimation/"
  output: "/home/hoangbm/pose_saved_model/output.json"
  result: '/home/hoangbm/lightweight_openpose_tensorflow/serving/test.jpg'
MODEL:
  saved_model_dir: "/home/hoangbm/pose_saved_model"
  tflite: "/home/hoangbm/pose.tflite"
  input_size: 368
  stride: 8
  upsample_ratio: 4
DATASET:
  annotations: '/home/hoangbm/datasets/coco2017'
  images_dir: '/mnt/ssd2/Datasets/COCO2017/images'
  json_dir: "/mnt/ssd2/Datasets/COCO2017/annotations"
  image: '/home/hoangbm/lightweight_openpose_tensorflow/serving/multi.jpg'
  dataset_type: "val"