MODEL:
  num_channels: 128
  num_stages: 1
  input_size: 368
EXPORT:
  format: 'sm'
  quantized: True
  saved_model: "/home/hoangbm/model_library/lw-pose/saved_model"
  tf_lite: "/home/hoangbm/model_library/lw-pose/poseT.tflite"
  checkpoint: "/home/hoangbm/checkpoint/pose-estimation/lw_pose_tf/ckpts/"
  frozen_pb: "/home/hoangbm/model_library/lw-pose"