MODEL:
  num_channels: 128
  num_stages: 1
  input_size: 368
EXPORT:
  format: 'sm'
  saved_model: "/home/hoang/pose_saved_model"
  tf_lite: "/home/hoang/pose.tflite"
  checkpoint: "/home/hoangbm/checkpoint/pose-estimation/lw_pose_tf/ckpts/"
  frozen_pb: "/home/hoangbm/"