MODEL:
  name: 'lw_mobilenetv2'
  num_channels: 128
  num_stages: 2
  input_size: 368
  mobile: True
  dataset: 'coco'
EXPORT:
  format: 'sm'
  quantized: True
  saved_model: "/home/hoangbm/model_library/lw-pose/coco_mbv2"
  tf_lite: "/home/hoangbm/model_library/lw-pose/poseT.tflite"
  checkpoint: "/mnt/hdd10tb/Users/hoangbm/checkpoint/pose-estimation/coco_lw_mobilenetv2_True/ckpts/"
  frozen_pb: "/home/hoangbm/model_library/lw-pose/coco_mbv2.pb"
  trt: "/home/hoangbm/model_library/lw-pose/coco_mbv2_trt"
GPU: "2"