MODEL:
  name: 'lw_mobilenetv2'
  num_channels: 128
  num_stages: 1
  input_size: 368
  mobile: True
  dataset: 'coco'
EXPORT:
  format: 'sm'
  quantized: True
  saved_model: "/home/hoang/model_library/lw-pose/saved_model_True"
  tf_lite: "/home/hoangbm/model_library/lw-pose/poseT.tflite"
  checkpoint: "/home/hoang/checkpoint/pose-estimation/coco_lw_mobilenetv2_True/ckpts/"
  frozen_pb: "/home/hoangbm/model_library/lw-pose/pose_s2.pb"