DATASET:
  name: 'kinect'
  annotation_dir: '/home/hoangbm/datasets/kinect/'
  image_dir: '/home/hoangbm/datasets/kinect'
  stride: 8
  sigma: 7
  paf_thickness: 1
  batch_size: 64
MODEL:
  name: 'lw_resnet50'
  num_channels: 128
  num_stages: 1
  num_joints: 19
  mobile: True
  input_size: 368