DATASET:
  name: 'coco'
  annotation_dir: '/home/hoangbm/datasets/coco2017/'
  image_dir: '/mnt/ssd2/Datasets/COCO2017/images'
  stride: 8
  sigma: 7
  paf_thickness: 1
  batch_size: 64
MODEL:
  name: 'lw_resnet50'
  num_channels: 128
  num_stages: 1
  num_joints: 19
  mobile: True
  input_size: 368