COMMON:
  GPU: '4,5'
  retrain: False
  saved_dir: "/home/hoangbm/checkpoint/pose-estimation/"
  saved_epochs: 5
MODEL:
  name: 'lw_shufflenetv2'
  num_channels: 128
  num_stages: 1
  input_size: 368
  mobile: True
DATASET:
  name: 'coco'
  annotation_dir: '/home/hoangbm/datasets/coco2017/'
  image_dir: '/mnt/ssd2/Datasets/COCO2017/images'
  stride: 8
  sigma: 7
  paf_thickness: 1
TRAIN:
  num_epochs: 50
  learning_rate: 0.0001
  decay_step: 5000
  decay_rate: 0.96
  batch_size: 40
VAL:
  batch_size: 40

