COMMON:
  GPU: '0,1'
  retrain: True
  saved_dir: "/home/hoang/checkpoint/pose-estimation/"
  saved_epochs: 2
MODEL:
  name: 'lw_mobilenetv2'
  num_channels: 128
  num_stages: 1
  input_size: 368
  mobile: True
DATASET:
  name: 'coco'
  annotation_dir: '/home/hoang/datasets/coco2017/'
  image_dir: '/mnt/hdd3tb/Datasets/COCO2017/images'
  stride: 8
  sigma: 7
  paf_thickness: 1
TRAIN:
  num_epochs: 60
  learning_rate: 0.00003
  decay_step: 5000
  decay_rate: 0.96
  batch_size: 56
VAL:
  batch_size: 56

