COMMON:
  GPU: '0,1,2'
  retrain: True
  saved_dir: "/home/hoangbm/checkpoint/pose-estimation/"
  saved_epochs: 5
MODEL:
  num_channels: 128
  num_stages: 1
  input_size: 368
  mobile: False
DATASET:
  name: 'coco'
  annotation_dir: '/home/hoangbm/datasets/coco2017/test/'
  image_dir: '/mnt/ssd2/Datasets/COCO2017/images'
  stride: 8
  sigma: 7
  paf_thickness: 1
TRAIN:
  num_epochs: 80
  learning_rate: 0.001
  decay_step: 5000
  decay_rate: 0.96
  batch_size: 60
VAL:
  batch_size: 60

