COMMON:
  GPU: '2,4,5'
  retrain: True
  saved_dir: "/home/hoangbm/checkpoint/pose-estimation/"
  saved_epochs: 2
MODEL:
  name: 'lw_resnet50'
  num_channels: 128
  num_stages: 1
  input_size: 368
  mobile: True
DATASET:
  name: 'coco'
  annotation_dir: '/home/hoangbm/datasets/coco2017/'
  image_dir: '/mnt/ssd2/BACKUP/Datasets/COCO2017/images'
  stride: 8
  sigma: 7
  paf_thickness: 1
TRAIN:
  num_epochs: 40
  learning_rate: 0.00053
  decay_step: 5000
  decay_rate: 0.9
  batch_size: 21
VAL:
  batch_size: 21

