COMMON:
  GPU: '1,2'
  retrain: True
  saved_dir: "/home/hoangbm/checkpoint/pose-estimation/"
  saved_epochs: 2
MODEL:
  num_channels: 128
  num_stages: 1
  input_size: 368
DATASET:
  annotation_dir: '/home/hoangbm/datasets/coco2017'
  image_dir: '/mnt/ssd2/Datasets/COCO2017/images'
  stride: 8
  sigma: 7
  paf_thickness: 1
TRAIN:
  num_epochs: 40
  learning_rate: 0.000005
  decay_step: 5000
  decay_rate: 0.96
  batch_size: 40
VAL:
  batch_size: 40

