COMMON:
  GPU: '5'
  device: 'CPU'
  saved_dir: "/home/hoangbm/checkpoint/pose-estimation/"
  output: "/tmp/output.json"
  result: '/home/hoangbm/lightweight_openpose_tensorflow/serving/tests/test.jpg'
MODEL:
  saved_model_dir: "/home/hoangbm/model_library/lw-pose/saved_model"
  tflite: "/home/hoangbm/model_library/lw-pose/poseT.tflite"
  mnn: "/home/hoangbm/model_library/lw-pose/pose.mnn"
  frozen_graph: "/home/hoangbm/model_library/lw-pose/pose_True.pb"
  openvino: '/home/hoangbm/model_library/lw-pose/openvino/lw_pose.xml'
  input_size: 368
  stride: 8
DATASET:
  annotations: "/mnt/ssd2/Datasets/COCO2017/annotations"
  images_dir: '/mnt/ssd2/Datasets/COCO2017/images'
  image: '/home/hoangbm/lightweight_openpose_tensorflow/serving/tests/cr7.jpg'
  dataset_type: "train"
  name: 'coco'

