COMMON:
  GPU: '1'
  saved_dir: "/home/hoangbm/checkpoint/pose-estimation/"
  output: "/tmp/output.json"
  result: '/home/hoang/lightweight_openpose_tensorflow/serving/test.jpg'
MODEL:
  saved_model_dir: "/home/hoang/pose_models/pose_saved_model"
  tflite: "/home/hoang/pose_models/poseT.tflite"
  mnn: "/home/hoang/pose_models/pose.mnn"
  frozen_graph: "/home/hoang/pose_models/pose.pb"
  input_size: 368
  stride: 8
DATASET:
  annotations: "/mnt/hdd3tb/Datasets/COCO2017/annotations"
  images_dir: '/mnt/hdd3tb/Datasets/COCO2017/images'
  image: '/home/hoang/lightweight_openpose_tensorflow/serving/process.jpeg'
  dataset_type: "train"