COMMON:
  GPU: '2'
  device: 'CPU'
  output: "/tmp/output.json"
  result: '/home/hoangbm/lightweight_openpose_tensorflow/serving/tests/test.jpg'
MODEL:
  saved_model_dir: "/home/hoangbm/model_library/lw-pose/resnet50"
  tflite: "/home/hoangbm/model_library/lw-pose/poseT.tflite"
  mnn: "/home/hoangbm/model_library/lw-pose/pose.mnn"
  frozen_graph: "/home/hoangbm/model_library/lw-pose/pose_s2.pb"
  openvino: '/home/hoangbm/model_library/lw-pose/openvino/lw_pose_16.xml'
  input_size: 368
  stride: 8
DATASET:
  annotations: "/mnt/ssd2/BACKUP/Datasets/COCO2017/annotations"
  images_dir: '/mnt/ssd2/BACKUP/Datasets/COCO2017/images'
  image: '/home/hoangbm/lightweight_openpose_tensorflow/serving/tests/m10.jpg'
  dataset_type: "val"
  name: 'coco'
